### ISSUE TITLE
autoscaler.yml no such file or directory

### ISSUE THREAD

**Issue by assinnata** [azionaventures/aziona-cli#19]
```
[EXCEPTION] None
[Errno 2] No such file or directory: 'autoscaler.yml'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/aziona/packages/kubernetes/kubeaction.py", line 149, in load
    kubeaction_exec(action=args.action, filename=manifest)
  File "/usr/lib/python3.9/site-packages/aziona/packages/kubernetes/kubeaction.py", line 67, in kubeaction_exec
    manifests.write(text.interpolation_file(filename))
  File "/usr/lib/python3.9/site-packages/aziona/core/text.py", line 149, in interpolation_file
    with open(filename, "r+") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'autoscaler.yml'

[EXCEPTION] None
Errore critico: Options allow_failure: DISATTIVO
Comando: python3 -m aziona.packages.kubernetes.kubeaction --blue-green True --check-container-sha256 True --wait-readiness True --manifest-path ./manifests/dev --manifest-yaml datadog.yml autoscaler.yml deployment.yml service.yml --after-readiness ingress.yml --kustomize-image DOCKER_IMAGE=***.dkr.ecr.eu-west-1.amazonaws.com/mirta/storefront:3c2b244e29b8b936-1268890104 --action apply
/usr/lib/python3.9/site-packages/aziona/packages/kubernetes/kubeaction.py:70: YAMLLoadWarning: calling yaml.load_all() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  for yml in data:
```

**Comment by assinnata** [comment]
risolto l'arcano era un errore di configurazione del .aziona.yml del progetto in cuii veniva forzato il passaggio dell'autoscaler
